import Head from 'next/head'
import React, {useState} from 'react'
import type {HelloResponse} from '~src/pages/api/hello'
import {Request} from '@simpli/serialized-request'
import {Await, AwaitActivity} from '~src/app/await'
import Navbar from '~src/components/Navbar'
import {AxiosResponse} from 'axios'

export default function Home() {
  const [value, setValue] = useState<string>()
  const [height, setHeight] = useState<number>()

  async function clickAction() {
    try {
      const promises: Promise<AxiosResponse>[] = [
        Request.post('/api/hello')
          .name('hello')
          .as<HelloResponse>()
          .delay(5000)
          .fetchResponse(),
        Request.get('/api/height')
          .name('height')
          .asNumber()
          .delay(3000)
          .fetchResponse(),
      ]

      await Await.run('populate', () => Promise.all(promises))

      setValue(value)
      setHeight(height)
    } catch {}
  }

  return (
    <>
      <Navbar />

      <div className={'typo min-h-screen-no-nav flex flex-col justify-center'}>
        <Head>
          <title>Hello world</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={'container flex flex-col items-center'}>
          <div className={'card card--padding-lg'}>
            <h1 className={'mb-4 text-5xl'}>Hello world</h1>

            <AwaitActivity name={'populate'}>
              <button className={'mb-4 btn'} onClick={clickAction}>
                Click me
              </button>

              <div className={'text-sm'}>Value: {value}</div>
              <div className={'text-sm'}>Height: {height}</div>
            </AwaitActivity>
          </div>
        </main>
      </div>
    </>
  )
}
