import Head from 'next/head'
import React from 'react'
import {useSelector} from 'react-redux'
import {RootStore} from '~src/store/RootStore'
import Navbar from '~src/components/Navbar'
import CardQuickSendGas from '~src/components/cards/CardQuickSendGas'
import TransitionShow from '~src/components/utils/TransitionShow'
import CardRegisteredCandidateStats from '~src/components/cards/CardRegisteredCandidateStats'
import CardCandidate from '~src/components/cards/CardCandidate'

export default function Home() {
  const {isConnected} = useSelector(RootStore.auth.getters)

  return (
    <>
      <Navbar />

      <div className={'typo min-h-screen-no-nav'}>
        <Head>
          <title>Neo Voting</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={'container'}>
          <TransitionShow if={isConnected}>
            <div className={'mb-4 flex'}>
              <CardCandidate className={'mr-4 flex-1'} />

              <CardQuickSendGas className={'flex-1'} />
            </div>
          </TransitionShow>

          <CardRegisteredCandidateStats className={'-mx-4'} />
        </main>
      </div>
    </>
  )
}
