import Head from 'next/head'
import React from 'react'
import Navbar from '~src/components/Navbar'
import CardHelloWorld from '~src/components/cards/CardHelloWorld'
import CardQuickSendGas from '~src/components/cards/CardQuickSendGas'
import {useSelector} from 'react-redux'
import {RootStore} from '~src/store/RootStore'

export default function Home() {
  const {isConnected} = useSelector(RootStore.auth.getters)

  return (
    <>
      <Navbar />

      <div className={'typo min-h-screen-no-nav flex flex-col justify-center'}>
        <Head>
          <title>Neo Voting</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={'container flex flex-col items-center'}>
          <div className={'w-96'}>
            <div>
              <CardQuickSendGas />
            </div>

            <div>
              <CardHelloWorld />
            </div>
          </div>
        </main>
      </div>
    </>
  )
}
