import Head from 'next/head'
import React, {useState} from 'react'
import type {HelloResponse} from '~/pages/api/hello'
import {Request} from '@simpli/serialized-request'

export default function Home() {
  const [value, setValue] = useState<string>()
  const [height, setHeight] = useState<number>()

  async function clickAction() {
    try {
      const {value} = await Request.post('/api/hello')
        .as<HelloResponse>()
        .getData()

      const height = await Request.get('/api/height').asNumber().getData()

      setValue(value)
      setHeight(height)
    } catch {}
  }

  return (
    <div className={'min-h-screen flex flex-col justify-center'}>
      <Head>
        <title>Hello world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'container flex flex-col items-center'}>
        <h1 className={'mb-4 text-5xl'}>Hello world</h1>

        <button
          className={
            'mb-4 transition bg-blue-800 text-white py-2 px-6 rounded hover:bg-blue-700'
          }
          onClick={clickAction}
        >
          Click me
        </button>

        <div className={'text-sm'}>Value: {value}</div>
        <div className={'text-sm'}>Height: {height}</div>
      </main>
    </div>
  )
}
